name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      custom_tag:
        description: 'Optional Docker tag (e.g. test, v1.2.3-dev)'
        required: false
        default: ''

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Extract Git info
        id: gitinfo
        run: |
          echo "REF_SLUG=${GITHUB_REF#refs/heads/}" >> "$GITHUB_OUTPUT"
          echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"

      - name: Set Docker tags
        id: set-tags
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/createultimateselection

          # Default tags
          TAGS=""
          CUSTOM_TAG="${{ github.event.inputs.custom_tag }}"

          if [[ -n "$CUSTOM_TAG" ]]; then
            TAGS="${IMAGE_NAME}:${CUSTOM_TAG}"
          elif [[ "${GITHUB_REF}" == refs/heads/main ]]; then
            TAGS="${IMAGE_NAME}:main,${IMAGE_NAME}:latest"
          elif [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            TAGS="${IMAGE_NAME}:${{ steps.gitinfo.outputs.TAG_NAME }}"
          fi

          echo "tags=${TAGS}" >> $GITHUB_OUTPUT
  
      - name: Extract metadata for Docker labels
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/createultimateselection

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.set-tags.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
